export const CREATE_REQUEST = 'CREATE_REQUEST';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';

// Login Session
export const CREATE_SESSION_REQUEST = 'CREATE_SESSION_REQUEST';
export const CREATE_SESSION_SUCCESS = 'CREATE_SESSION_SUCCESS';
export const CREATE_SESSION_FAILURE = 'CREATE_SESSION_FAILURE';

// TASKS LIST
export const DELETE_TASKSLIST_REQUEST = 'DELETE_TASKSLIST_REQUEST';
export const DELETE_TASKSLIST_SUCCESS = 'DELETE_TASKSLIST_SUCCESS';
export const DELETE_TASKSLIST_FAILURE = 'DELETE_TASKSLIST_FAILURE';
export const INSERT_TASKSLIST_REQUEST = 'INSERT_TASKSLIST_REQUEST';
export const INSERT_TASKSLIST_SUCCESS = 'INSERT_TASKSLIST_SUCCESS';
export const INSERT_TASKSLIST_FAILURE = 'INSERT_TASKSLIST_FAILURE';
export const UPDATE_TASKSLIST_REQUEST = 'UPDATE_TASKSLIST_REQUEST';
export const UPDATE_TASKSLIST_SUCCESS = 'UPDATE_TASKSLIST_SUCCESS';
export const UPDATE_TASKSLIST_FAILURE = 'UPDATE_TASKSLIST_FAILURE';

// TASKS
export const DELETE_TASK_REQUEST = 'DELETE_TASK_REQUEST';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_FAILURE = 'DELETE_TASK_FAILURE';
export const FETCH_TASKS_REQUEST = 'FETCH_TASKS_REQUEST';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAILURE = 'FETCH_TASKS_FAILURE';
export const INSERT_TASK_REQUEST = 'INSERT_TASK_REQUEST';
export const INSERT_TASK_SUCCESS = 'INSERT_TASK_SUCCESS';
export const INSERT_TASK_FAILURE = 'INSERT_TASK_FAILURE';
export const UPDATE_TASK_REQUEST = 'UPDATE_TASK_REQUEST';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
export const UPDATE_TASK_FAILURE = 'UPDATE_TASK_FAILURE';

// TASKS SORT ORDER
export const SET_TASK_VIEWTYPE = 'SET_TASK_VIEWTYPE';